version: '2'

services:
    payment:
        # environment:
        #     - AUTH_BY=Johmby
        build: 
            context: .
            dockerfile: docker/payment/Dockerfile
        image: runwhendemo/payment
        hostname: payment
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        ports:
            - "8082:8080"
